In [1]:
from queue import PriorityQueue, LifoQueue
import numpy as np
import random as rnd

In [2]:
class Cell: 
    def __init__(self, row, col, prev = None):
        self.row = row
        self.col = col
        self.prev = prev
    def __lt__(self, other):        
        if (self.row == other.row):
            return self.col < other.col
        return self.row < other.row
    def __eq__(self, other):
        return self.row == other.row and self.col == other.col and self.prev is other.prev
    def __str__(self):
        return "(" + str(self.row) + ", " + str(self.col) + ") :: prev=" + ("NONE" if self.prev is None else "(" + str(self.prev.row) + ", " + str(self.prev.col) + ")")
    def __repr__(self):
        return "(" + str(self.row) + ", " + str(self.col) + ") :: prev=" + ("NONE" if self.prev is None else "(" + str(self.prev.row) + ", " + str(self.prev.col) + ")")

In [3]:
class Maze:
    # -1 is barrier, 0 is free
    def __init__(self, dim, p, q = 0):
        self.board =  np.zeros([dim, dim], dtype=int)
        self.dim = dim
        self.currentfire = []
        self.q = q
        self.p = p
        obstaclesList = []
        for i in range(0, dim): #range() generates a list from 0 to dim-1 which can take up a lot of memory
            for j in range(0, dim):             
                if(rnd.random() < p):
                    self.board[i, j] = -1
                    obstaclesList.append((i, j))
        self.obstacles = np.array(obstaclesList)
        self.board[0, 0] = 0
        self.board[dim - 1, dim - 1] = 0

    def isSolvable(self):
        return pathExists(self)
    
    def startFire(self):
        i = rnd.randint(0,self.dim-1)
        j = rnd.randint(0,self.dim-1)
        while(self.board[i,j] == -1 or (i==0 and j == 0) or (i == self.dim-1 and j == self.dim-1)):
            i = rnd.randint(0,self.dim-1)
            j = rnd.randint(0,self.dim-1)
        self.board[i,j] = 2
        self.currentfire.append([i,j,None])
    
    def iterateFire(self):
        visited = [] #neighbors already visited in current iteration
        nowonfire = [] #need to append all new fires at the end 
        for f in self.currentfire:
            if(f[2] != 0): #check to see if all neighbors are already on fire. 
                neighbors = findAllNeighbors(f[0:2],self) #calculate valid neighbors of f, the cell that is currently on fire
                ofnbor = 0 #counter to find out how many neighbors are on fire
                for n in neighbors: #loop through the neighbors of f
                    nr,nc = n 
                    if (self.board[nr,nc] == 2): 
                        ofnbor = ofnbor + 1 
                    else:
                        if(n[0:2] not in visited): #only roll once for each cell not on fire
                            if(self.board[nr,nc] != -1):
                                surroundings = findAllNeighbors(n[0:2],self) #see what the neighbors are for the neighbor of f
                                k = 0 #k will be guaranteed to be at least 1
                                for nn in surroundings:
                                    nnr,nnc = nn
                                    if(self.board[nnr,nnc] == 2):
                                        k = k + 1 #counter
                                if(rnd.random() <= (1-((1-self.q)**k))): #roll
                                    self.board[nr,nc] = 2 
                                    nowonfire.append([nr,nc,None])
                                    ofnbor = ofnbor + 1
                                else:
                                    visited.append([nr,nc])
                if(ofnbor == len(neighbors)):
                        f[2] = 0
        if(nowonfire):
            for x in nowonfire:
                self.currentfire.append(x)

In [4]:
def pathExists(maze, fromCoords = (0,0), toCoords = None):
    if toCoords is None:
        toCoords = (maze.dim - 1, maze.dim - 1)
    toRow, toCol = toCoords
    visited = set()
    fringe = LifoQueue()
    fringe.put(fromCoords)
    while not fringe.empty():
        currentCoords = fringe.get()
        currentRow, currentCol = currentCoords
        if (currentRow == toRow and currentCol == toCol):
            return True
        else:
            neighbors = findNeighboringCoords(currentCoords, maze)
            for neighbor in neighbors:
                if neighbor in visited:
                    continue
                fringe.put(neighbor)
            visited.add(currentCoords)
    return False

In [5]:
def findNeighboringCoords(coords, maze):
    cellRow, cellCol = coords
    potentialNeighbors = [(cellRow + 1, cellCol), (cellRow - 1, cellCol), (cellRow, cellCol - 1), (cellRow, cellCol + 1)]
    neighbors = []
    for potentialNeighbor in potentialNeighbors:
        row, col = potentialNeighbor
        if (row >= maze.dim or row < 0 or col >= maze.dim or col < 0 or maze.board[row,col] != 0):
            continue
        neighbors.append(potentialNeighbor)
    return neighbors

def findNeighboringCells(cell, maze):
    neighboringCoords = findNeighboringCoords((cell.row, cell.col), maze)
    neighbors = []
    for neighbor in neighboringCoords:
        row, col = neighbor
        neighbors.append(Cell(row, col, cell))
    return neighbors

def findAllNeighbors(coords,maze): 
    cellRow, cellCol = coords
    potentialNeighbors = [(cellRow + 1, cellCol), (cellRow - 1, cellCol), (cellRow, cellCol - 1), (cellRow, cellCol + 1)]
    neighbors = []
    for potentialNeighbor in potentialNeighbors:
        row, col = potentialNeighbor
        if (row >= maze.dim or row < 0 or col >= maze.dim or col < 0 or maze.board[row,col] == -1):
            continue
        neighbors.append(potentialNeighbor)
    return neighbors

In [6]:
def uniformCost(maze, cell):
    return 1
def shortestPathSearch(maze, startCoords = (0, 0), heuristicFunction = uniformCost, findNeighbors = findNeighboringCells):
    startRow, startCol = startCoords
    startCell = Cell(startRow, startCol)
    visited = set()
    fringe = PriorityQueue()
    fringe.put((0, startCell))
    while not fringe.empty():
        pathLength, currentCell = fringe.get()
        if (currentCell.row == maze.dim - 1 and currentCell.col == maze.dim - 1):
            shortestPath = []
            while (currentCell != startCell):
                shortestPath.append((currentCell.row, currentCell.col))
                currentCell = currentCell.prev
            shortestPath.append((startRow, startCol))
            shortestPath.reverse()
            return shortestPath
        else:
            neighbors = findNeighbors(cell = currentCell, maze = maze)
            for neighbor in neighbors:
                if (neighbor.row, neighbor.col) in visited:
                    continue
                nextPathLength = pathLength + heuristicFunction(maze = maze, cell = neighbor)
                fringe.put((nextPathLength, neighbor))
            visited.add((currentCell.row, currentCell.col))
    return None

In [29]:
def run_secondStrat(maze):
    """
    Algorithm:
    1. Identify shortest path to goal
        1.1. If found, move agent according to path
        1.2. Else, keep the agent in place
    2. Check if the agent reached the goal
        2.1. If true, terminate and return success
        2.2. Else, continue
    3. Advance the fire and check if the agent is burned
        3.1. If burned, terminate and return failure
        3.2. Else, continue at step 1
    """
    m = maze
    m.startFire()
    agent = (0,0)
    while True: #Loop exit conditions: Agent reaches goal or agent gets burned
        shortestPath = shortestPathSearch(m, agent) #recalculate the shortest path from the agent to the goal at agent's turn
        if shortestPath != None: #if a shortest path was found, move the agent in that direction
            agent = shortestPath[1]
        if agent == (m.dim-1, m.dim-1): #returns true if the agent reaches the goal, otherwise continue
            print("Agent Reached Goal")
            return True
        m.iterateFire() #advances the fire immediately after the agent's turn
        if m.board[agent] == 2: #returns false if the fire reaches the agent, otherwise continue
            print("Agent Burned")
            return False

In [30]:
m1 = Maze(10,0.2,0.2)
while m1 is None or not m1.isSolvable():
    m1 = Maze(10,0.2,0.2)
print(m1.board)
run_secondStrat(m1)

[[ 0  0  0  0 -1 -1 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 -1]
 [-1 -1  0 -1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1  0 -1  0 -1  0 -1]
 [ 0  0  0  0  0  0  0  0 -1  0]
 [ 0  0  0 -1  0  0  0  0  0 -1]
 [-1  0  0  0  0  0 -1  0  0  0]
 [ 0 -1  0 -1  0  0  0  0 -1  0]
 [-1 -1 -1  0  0  0 -1  0  0  0]]
Agent Reached Goal


True