In [1]:
import import_ipynb
from maze_common import Maze, shortestPathSearch
import random as rnd
import numpy as np
import copy

importing Jupyter notebook from maze_common.ipynb


In [21]:
maze = Maze(10, .3)
print(maze.board)

def manhattanDistance(maze, cell):
    return abs(cell.row - (maze.dim - 1)) + abs(cell.col - (maze.dim - 1))

if (maze.isSolvable()):
    shortestPath = shortestPathSearch(maze, heuristicFunction = manhattanDistance)
    print(shortestPath)

[[ 0  0 -1  0  0  0  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0 -1 -1]
 [-1  0 -1  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1  0 -1  0  0 -1]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0 -1  0  0 -1 -1  0  0]
 [ 0 -1  0 -1 -1 -1  0  0  0 -1]
 [-1  0  0 -1 -1  0  0  0  0 -1]
 [-1  0 -1  0  0  0 -1 -1  0  0]
 [ 0  0 -1  0  0 -1  0 -1 -1  0]]
[(1, 0), (1, 1), (1, 2), (1, 3), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 7), (4, 7), (4, 8), (5, 8), (6, 8), (7, 8), (8, 8), (8, 9), (9, 9)]


In [3]:
def thinMaze(maze, fractionRemove):
    numRemove = round(fractionRemove * maze.obstacles.size / 2)
    thinMaze = copy.deepcopy(maze)
    for i in range(0,numRemove):
        indexRemove = int(rnd.random() * thinMaze.obstacles.size / 2)
        obstacleX, obstacleY = thinMaze.obstacles[indexRemove]
        thinMaze.obstacles = np.delete(thinMaze.obstacles,indexRemove, axis=0)
        thinMaze.board[obstacleX][obstacleY] = 0
    return thinMaze
    
maze = Maze(5, .5)
thinnedMaze = thinMaze(maze, .6)
print("Original obstacles:\n", maze.obstacles)
print("Thinned obstacles:\n", thinnedMaze.obstacles)

Original obstacles:
 [[0 0]
 [0 3]
 [1 0]
 [1 1]
 [1 3]
 [1 4]
 [2 0]
 [2 4]
 [3 0]
 [3 2]
 [3 3]
 [4 2]
 [4 3]]
Thinned obstacles:
 [[1 0]
 [1 4]
 [3 2]
 [3 3]
 [4 2]]
