In [1]:
import import_ipynb
from maze_common import Maze, shortestPathSearch, Cell
import time
import random as rnd
import numpy as np
import copy

importing Jupyter notebook from maze_common.ipynb
[[ 0  0 -1 -1 -1  0 -1  0  0  0  0  0 -1 -1 -1]
 [ 0  0  0 -1  0  0  0 -1  0  0  0  0  0 -1  0]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0  0 -1 -1  0  0  0 -1]
 [-1  0 -1  0  0  0  0 -1  0  0  0 -1  0 -1 -1]
 [ 0  0 -1  0 -1  0 -1  0  0  0  0  0  0  0  0]
 [-1 -1 -1  0  0 -1 -1  0  0 -1  0  0  0 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0 -1 -1  0  0]
 [ 0 -1  0  0  0 -1  0 -1  0  0  0 -1  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0  0 -1 -1  0 -1]
 [ 0 -1 -1  0  0 -1  0 -1  0 -1  0 -1  0  0  0]
 [ 0  0 -1  0  0  0  0  0 -1  0  0  0  0  0 -1]
 [ 0  0  0  0 -1  0  0  0  0 -1  0  0  0  0  0]
 [ 0  0  0 -1  0 -1 -1  0 -1  0  0  0  0  0  0]
 [ 0  0 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1  0]]
[[ 0  0 -1 -1 -1  0 -1  0  0  0  0  0 -1 -1 -1]
 [ 0  0  0 -1  0  0  0 -1  0  0  0  0  0 -1  0]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0  0 -1 -1  0  0  0 -1]
 [-1  0 -1  0  0  0  0 -1  0  0  0 -1

In [82]:
maze = Maze(22, .3)
solvable = maze.isSolvable()
print("Is solvable?", solvable)
print("Obstacles?", maze.obstacles.shape[0])

Is solvable? True
Obstacles? 138


In [83]:
def manhattanDistance(maze, cell):
    return ((maze.dim - 1) - cell.row) + ((maze.dim - 1) - cell.col)

if (solvable):
    startTime = time.time()
    print(maze.board)
    print(maze.obstacles.shape[0], "obstacles")
    shortestPath = shortestPathSearch(maze, heuristicFunction = manhattanDistance)
    print("***** Found shortest path in %s seconds *****" % (time.time() - startTime))
    print(shortestPath)
    

[[ 0  0  0  0  0  0  0  0 -1  0  0  0 -1  0 -1  0  0  0 -1 -1  0  0]
 [ 0  0  0 -1 -1 -1 -1  0  0  0 -1 -1  0  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0 -1  0  0 -1  0  0  0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0 -1  0  0  0 -1  0  0 -1  0 -1 -1  0 -1  0  0]
 [-1  0  0 -1  0 -1  0  0  0  0  0  0  0  0 -1  0  0  0 -1  0  0  0]
 [-1  0  0  0  0  0  0  0  0 -1  0  0 -1  0 -1  0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0  0  0 -1  0 -1  0 -1  0 -1 -1  0 -1  0 -1  0]
 [ 0  0 -1  0  0 -1  0 -1 -1 -1 -1 -1  0  0  0  0 -1  0 -1  0 -1  0]
 [-1  0 -1  0 -1 -1  0 -1 -1 -1  0  0  0  0 -1  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0 -1  0  0  0  0  0 -1  0  0  0 -1  0  0  0]
 [-1 -1  0  0  0  0  0 -1 -1 -1  0  0 -1  0  0  0  0 -1  0  0  0 -1]
 [ 0  0 -1  0 -1  0 -1  0  0 -1  0 -1 -1  0  0  0  0  0  0 -1  0  0]
 [ 0 -1  0 -1  0  0 -1  0  0  0  0  0  0  0 -1  0  0  0  0 -1 -1  0]
 [ 0  0 -1  0 -1  0 -1  0  0  0 -1  0  0 -1  0 -1  0 -1  0  0  0 -1]
 [ 0 -1 -1  0  0  0  0  0  0  0 -1

In [14]:
def thinMaze(maze, fractionRemove):
    thinMaze = Maze(1, 0)
    thinMaze.board = copy.deepcopy(maze.board)
    thinMaze.obstacles = copy.deepcopy(maze.obstacles)
    thinMaze.dim = maze.dim
    numRemove = round(fractionRemove * thinMaze.obstacles.shape[0])
    for i in range(0,numRemove):
        indexRemove = int(rnd.random() * thinMaze.obstacles.shape[0])
        obstacleX, obstacleY = thinMaze.obstacles[indexRemove]
        thinMaze.obstacles = np.delete(thinMaze.obstacles,indexRemove, axis=0)
        thinMaze.board[obstacleX, obstacleY] = Cell.OPEN
    return thinMaze
    
thinnedMaze = thinMaze(maze, .05)
print("Original obstacles: ", maze.obstacles.shape[0], "\n", maze.obstacles)
print("Thinned obstacles: ", thinnedMaze.obstacles.shape[0], "\n",thinnedMaze.obstacles)
print("Thinned maze:\n", thinnedMaze.board)

Original obstacles:  56 
 [[ 0  5]
 [ 0  8]
 [ 0 14]
 [ 1  0]
 [ 1  2]
 [ 1  5]
 [ 1  9]
 [ 1 14]
 [ 2  2]
 [ 2  3]
 [ 2  6]
 [ 2  9]
 [ 4  0]
 [ 4  2]
 [ 4  5]
 [ 4  6]
 [ 4 12]
 [ 5  0]
 [ 5 11]
 [ 5 12]
 [ 6  5]
 [ 6  6]
 [ 6 10]
 [ 7  1]
 [ 7  2]
 [ 7  6]
 [ 7  7]
 [ 7  8]
 [ 7 10]
 [ 8  1]
 [ 8  3]
 [ 8 11]
 [ 8 13]
 [ 9  9]
 [ 9 11]
 [ 9 12]
 [ 9 14]
 [10  2]
 [10  3]
 [10  4]
 [10  7]
 [10  9]
 [11  5]
 [11  7]
 [11  9]
 [11 11]
 [12  0]
 [12  7]
 [12 10]
 [13  0]
 [13  1]
 [13  6]
 [13  7]
 [13  9]
 [14  7]
 [14 10]]
Thinned obstacles:  53 
 [[ 0  5]
 [ 0  8]
 [ 0 14]
 [ 1  2]
 [ 1  9]
 [ 1 14]
 [ 2  2]
 [ 2  3]
 [ 2  6]
 [ 2  9]
 [ 4  0]
 [ 4  2]
 [ 4  5]
 [ 4  6]
 [ 4 12]
 [ 5 11]
 [ 5 12]
 [ 6  5]
 [ 6  6]
 [ 6 10]
 [ 7  1]
 [ 7  2]
 [ 7  6]
 [ 7  7]
 [ 7  8]
 [ 7 10]
 [ 8  1]
 [ 8  3]
 [ 8 11]
 [ 8 13]
 [ 9  9]
 [ 9 11]
 [ 9 12]
 [ 9 14]
 [10  2]
 [10  3]
 [10  4]
 [10  7]
 [10  9]
 [11  5]
 [11  7]
 [11  9]
 [11 11]
 [12  0]
 [12  7]
 [12 10]
 [13  0]
 [13  1]
 [13  6]
 [1

In [15]:
visited = {}

def thinnedMazeShortestPathLength(maze, cell):
    shortestPathLength = 0
    if ((cell.row, cell.col)) not in visited:
        shortestPath = shortestPathSearch(thinnedMaze, startCoords = (cell.row, cell.col))
        shortestPathLength = len(shortestPath)
        for i in range(0, shortestPathLength):
            row, col = shortestPath[i]
            if ((row, col)) in visited: 
                break
            else:
                visited[(row, col)] = shortestPathLength - i - 1
    else:
        shortestPathLength = visited[(cell.row, cell.col)]
    return shortestPathLength

if (solvable):
    startTime = time.time()
    shortestPath = shortestPathSearch(maze, heuristicFunction = thinnedMazeShortestPathLength)
    print("***** Found shortest path in %s seconds *****" % (time.time() - startTime))
    print(shortestPath)

***** Found shortest path in 10.846683263778687 seconds *****
[(0, 0), (0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (5, 2), (5, 3), (6, 3), (6, 4), (7, 4), (7, 5), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9), (8, 10), (9, 10), (10, 10), (10, 11), (10, 12), (11, 12), (12, 12), (12, 13), (13, 13), (13, 14), (14, 14)]
