In [1]:
import import_ipynb
from maze_common import Maze, shortestPathSearch
import random as rnd
import numpy as np
import copy

importing Jupyter notebook from maze_common.ipynb


In [3]:
maze = Maze(10, .3)
solvable = maze.isSolvable()
print(maze.board, "\nIs solvable? ", solvable)

[[ 0  0 -1  0  0 -1  0  0 -1  0]
 [ 0  0  0  0  0 -1  0  0  0  0]
 [ 0 -1  0 -1  0  0 -1  0  0  0]
 [-1  0  0  0 -1  0  0 -1  0 -1]
 [-1  0  0 -1  0 -1  0 -1  0  0]
 [-1  0  0 -1  0 -1  0  0  0  0]
 [ 0  0  0  0  0 -1  0 -1  0  0]
 [ 0 -1 -1 -1 -1  0  0  0 -1  0]
 [-1 -1 -1  0  0  0 -1  0  0 -1]
 [ 0 -1 -1 -1  0 -1  0 -1  0  0]] 
Is solvable?  True


In [4]:
def manhattanDistance(maze, cell):
    return abs(cell.row - (maze.dim - 1)) + abs(cell.col - (maze.dim - 1))

if (solvable):
    shortestPath = shortestPathSearch(maze, heuristicFunction = manhattanDistance)
    print(shortestPath)

[(0, 0), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (2, 4), (2, 5), (3, 5), (3, 6), (4, 6), (5, 6), (6, 6), (7, 6), (7, 7), (8, 7), (8, 8), (9, 8), (9, 9)]


In [5]:
def thinMaze(maze, fractionRemove):
    numRemove = round(fractionRemove * maze.obstacles.size / 2)
    thinMaze = copy.deepcopy(maze)
    for i in range(0,numRemove):
        indexRemove = int(rnd.random() * thinMaze.obstacles.size / 2)
        obstacleX, obstacleY = thinMaze.obstacles[indexRemove]
        thinMaze.obstacles = np.delete(thinMaze.obstacles,indexRemove, axis=0)
        thinMaze.board[obstacleX][obstacleY] = 0
    return thinMaze
    
thinnedMaze = thinMaze(maze, .6)
print("Original obstacles:\n", maze.obstacles)
print("Thinned obstacles:\n", thinnedMaze.obstacles)

Original obstacles:
 [[0 2]
 [0 5]
 [0 8]
 [1 5]
 [2 1]
 [2 3]
 [2 6]
 [3 0]
 [3 4]
 [3 7]
 [3 9]
 [4 0]
 [4 3]
 [4 5]
 [4 7]
 [5 0]
 [5 3]
 [5 5]
 [6 5]
 [6 7]
 [7 1]
 [7 2]
 [7 3]
 [7 4]
 [7 8]
 [8 0]
 [8 1]
 [8 2]
 [8 6]
 [8 9]
 [9 1]
 [9 2]
 [9 3]
 [9 5]
 [9 7]
 [9 9]]
Thinned obstacles:
 [[3 0]
 [3 7]
 [4 3]
 [4 7]
 [5 3]
 [5 5]
 [6 5]
 [6 7]
 [7 2]
 [7 8]
 [8 2]
 [9 3]
 [9 7]
 [9 9]]


In [7]:
def thinnedMazeShortestPathLength(maze, cell):
    return shortestPathSearch(thinnedMaze, startCoords = (cell.row, cell.col))

if (solvable):
    shortestPath = shortestPathSearch(maze, heuristicFunction = thinnedMazeShortestPathLength)
    print(shortestPath)

TypeError: uniformCost() takes 0 positional arguments but 2 were given